create extension if not exists "fuzzystrmatch" with schema "extensions";

create extension if not exists "pgjwt" with schema "extensions";


create table "public"."audiences" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "description" text,
    "is_active" boolean default true,
    "created_at" timestamp without time zone default now()
);


alter table "public"."audiences" enable row level security;

create table "public"."bank_account_verifications" (
    "id" uuid not null default gen_random_uuid(),
    "supplier_id" uuid,
    "verification_code" text not null,
    "email_sent_to" text not null,
    "expires_at" timestamp with time zone not null,
    "is_used" boolean default false,
    "verification_type" text not null,
    "pending_data" jsonb,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."bank_account_verifications" enable row level security;

create table "public"."categories" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "icon" text,
    "is_active" boolean default true,
    "created_at" timestamp without time zone default now()
);


alter table "public"."categories" enable row level security;

create table "public"."category_fields" (
    "id" uuid not null default gen_random_uuid(),
    "category" text not null,
    "field_key" text not null,
    "label" text,
    "type" text,
    "is_required" boolean default false,
    "is_filterable" boolean default false,
    "created_at" timestamp with time zone default now(),
    "test_field_x" text
);


alter table "public"."category_fields" enable row level security;

create table "public"."concepts" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "type" text not null,
    "is_active" boolean default true,
    "created_at" timestamp without time zone default now()
);


alter table "public"."concepts" enable row level security;

create table "public"."empowerment_products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."empowerment_products" enable row level security;

create table "public"."images" (
    "id" uuid not null default gen_random_uuid(),
    "product_id" uuid,
    "image_url" text not null
);


alter table "public"."images" enable row level security;

create table "public"."orders" (
    "id" uuid not null default gen_random_uuid(),
    "product_id" uuid,
    "customer_name" text not null,
    "customer_email" text not null,
    "event_date" date not null,
    "quantity" integer not null default 1,
    "total_price" numeric(12,2) not null,
    "status" text default 'pending'::text,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
);


alter table "public"."orders" enable row level security;

create table "public"."product_variants" (
    "id" uuid not null default gen_random_uuid(),
    "product_id" uuid,
    "variant_name" text not null,
    "variant_value" text not null,
    "price" numeric(12,2) not null
);


alter table "public"."product_variants" enable row level security;

create table "public"."products" (
    "id" uuid not null default gen_random_uuid(),
    "supplier_id" uuid,
    "subcategory_id" uuid,
    "name" text not null,
    "description" text,
    "cover_image" text,
    "video_url" text,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
);


alter table "public"."products" enable row level security;

create table "public"."provider_availability_slots" (
    "id" uuid not null default gen_random_uuid(),
    "service_id" uuid,
    "date" date,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "is_available" boolean default true,
    "current_bookings" integer default 0,
    "max_concurrent_bookings" integer default 1
);


alter table "public"."provider_availability_slots" enable row level security;

create table "public"."providers" (
    "id" uuid not null default gen_random_uuid(),
    "name" text,
    "calendar_connected" boolean default false,
    "calendar_active" boolean default false
);


alter table "public"."providers" enable row level security;

create table "public"."reviews" (
    "id" uuid not null default gen_random_uuid(),
    "supplier_id" uuid,
    "customer_name" text not null,
    "customer_email" text not null,
    "rating" integer not null,
    "review_text" text not null,
    "status" text not null default 'pending'::text,
    "is_staged" boolean default false,
    "response_text" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."reviews" enable row level security;

create table "public"."services" (
    "id" uuid not null default gen_random_uuid(),
    "provider_id" uuid,
    "name" text,
    "service_areas" text[],
    "setup_time_minutes" integer default 30,
    "teardown_time_minutes" integer default 15,
    "is_visible" boolean default true,
    "base_price" numeric,
    "has_calendar_integration" boolean default false
);


alter table "public"."services" enable row level security;

create table "public"."subcategories" (
    "id" uuid not null default gen_random_uuid(),
    "category_id" uuid,
    "name" text not null,
    "is_active" boolean default true,
    "created_at" timestamp without time zone default now(),
    "icon" text
);


alter table "public"."subcategories" enable row level security;

create table "public"."subcategory_custom_fields" (
    "id" uuid not null default gen_random_uuid(),
    "subcategory_id" uuid,
    "field_key" text not null,
    "label" text not null,
    "field_type" text,
    "options" text[],
    "is_required" boolean default false,
    "is_filter" boolean default false,
    "priority" integer default 0,
    "created_at" timestamp without time zone default now(),
    "display_order" integer default 0
);


alter table "public"."subcategory_custom_fields" enable row level security;

create table "public"."subconcepts" (
    "id" uuid not null default gen_random_uuid(),
    "concept_id" uuid,
    "name" text not null,
    "is_active" boolean default true,
    "created_at" timestamp without time zone default now()
);


alter table "public"."subconcepts" enable row level security;

create table "public"."supplier_bank_accounts" (
    "id" uuid not null default gen_random_uuid(),
    "supplier_id" uuid,
    "bank_name" text not null,
    "bank_code" text not null,
    "branch_number" text not null,
    "account_number" text not null,
    "account_holder_name" text not null,
    "iban" text,
    "swift_code" text,
    "bank_document_url" text,
    "verification_status" text default 'pending'::text,
    "verification_notes" text,
    "requires_2fa_verification" boolean default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."supplier_bank_accounts" enable row level security;

create table "public"."suppliers" (
    "id" uuid not null default gen_random_uuid(),
    "business_name" text not null,
    "business_type" text not null,
    "tax_id" text not null,
    "description" text,
    "profile_image" text,
    "cover_image" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "is_active" boolean not null default true,
    "is_suspended" boolean not null default false
);


alter table "public"."suppliers" enable row level security;

create table "public"."test_force_migration" (
    "id" uuid not null default gen_random_uuid(),
    "name" text
);


alter table "public"."test_force_migration" enable row level security;

create table "public"."test_sync" (
    "id" uuid not null default gen_random_uuid(),
    "label" text
);


alter table "public"."test_sync" enable row level security;

create table "public"."upsell_products" (
    "id" uuid not null default gen_random_uuid(),
    "upsell_id" uuid,
    "product_id" uuid,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."upsell_products" enable row level security;

create table "public"."upsells" (
    "id" uuid not null default gen_random_uuid(),
    "supplier_id" uuid,
    "title" text not null,
    "description" text,
    "original_price" numeric(10,2) not null,
    "discounted_price" numeric(10,2),
    "discount_percentage" integer,
    "is_active" boolean default true,
    "valid_from" timestamp with time zone default now(),
    "valid_until" timestamp with time zone,
    "max_uses" integer,
    "current_uses" integer default 0,
    "terms_and_conditions" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."upsells" enable row level security;

CREATE UNIQUE INDEX audiences_pkey ON public.audiences USING btree (id);

CREATE UNIQUE INDEX bank_account_verifications_pkey ON public.bank_account_verifications USING btree (id);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX category_fields_pkey ON public.category_fields USING btree (id);

CREATE UNIQUE INDEX concepts_pkey ON public.concepts USING btree (id);

CREATE UNIQUE INDEX empowerment_products_pkey ON public.empowerment_products USING btree (id);

CREATE INDEX idx_bank_account_verifications_code ON public.bank_account_verifications USING btree (verification_code);

CREATE INDEX idx_bank_account_verifications_expires_at ON public.bank_account_verifications USING btree (expires_at);

CREATE INDEX idx_bank_account_verifications_supplier_id ON public.bank_account_verifications USING btree (supplier_id);

CREATE INDEX idx_reviews_created_at ON public.reviews USING btree (created_at DESC);

CREATE INDEX idx_reviews_rating ON public.reviews USING btree (rating);

CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);

CREATE INDEX idx_reviews_supplier_id ON public.reviews USING btree (supplier_id);

CREATE INDEX idx_supplier_bank_accounts_supplier_id ON public.supplier_bank_accounts USING btree (supplier_id);

CREATE INDEX idx_supplier_bank_accounts_verification_status ON public.supplier_bank_accounts USING btree (verification_status);

CREATE INDEX idx_upsell_products_product_id ON public.upsell_products USING btree (product_id);

CREATE INDEX idx_upsell_products_upsell_id ON public.upsell_products USING btree (upsell_id);

CREATE INDEX idx_upsells_is_active ON public.upsells USING btree (is_active);

CREATE INDEX idx_upsells_supplier_id ON public.upsells USING btree (supplier_id);

CREATE INDEX idx_upsells_valid_until ON public.upsells USING btree (valid_until);

CREATE UNIQUE INDEX images_pkey ON public.images USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX product_variants_pkey ON public.product_variants USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX provider_availability_slots_pkey ON public.provider_availability_slots USING btree (id);

CREATE UNIQUE INDEX providers_pkey ON public.providers USING btree (id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);

CREATE UNIQUE INDEX services_pkey ON public.services USING btree (id);

CREATE UNIQUE INDEX subcategories_pkey ON public.subcategories USING btree (id);

CREATE UNIQUE INDEX subcategory_custom_fields_pkey ON public.subcategory_custom_fields USING btree (id);

CREATE UNIQUE INDEX subconcepts_pkey ON public.subconcepts USING btree (id);

CREATE UNIQUE INDEX supplier_bank_accounts_pkey ON public.supplier_bank_accounts USING btree (id);

CREATE UNIQUE INDEX supplier_bank_accounts_supplier_id_key ON public.supplier_bank_accounts USING btree (supplier_id);

CREATE UNIQUE INDEX suppliers_pkey ON public.suppliers USING btree (id);

CREATE UNIQUE INDEX suppliers_tax_id_key ON public.suppliers USING btree (tax_id);

CREATE UNIQUE INDEX test_force_migration_pkey ON public.test_force_migration USING btree (id);

CREATE UNIQUE INDEX test_sync_pkey ON public.test_sync USING btree (id);

CREATE UNIQUE INDEX upsell_products_pkey ON public.upsell_products USING btree (id);

CREATE UNIQUE INDEX upsell_products_upsell_id_product_id_key ON public.upsell_products USING btree (upsell_id, product_id);

CREATE UNIQUE INDEX upsells_pkey ON public.upsells USING btree (id);

alter table "public"."audiences" add constraint "audiences_pkey" PRIMARY KEY using index "audiences_pkey";

alter table "public"."bank_account_verifications" add constraint "bank_account_verifications_pkey" PRIMARY KEY using index "bank_account_verifications_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."category_fields" add constraint "category_fields_pkey" PRIMARY KEY using index "category_fields_pkey";

alter table "public"."concepts" add constraint "concepts_pkey" PRIMARY KEY using index "concepts_pkey";

alter table "public"."empowerment_products" add constraint "empowerment_products_pkey" PRIMARY KEY using index "empowerment_products_pkey";

alter table "public"."images" add constraint "images_pkey" PRIMARY KEY using index "images_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."product_variants" add constraint "product_variants_pkey" PRIMARY KEY using index "product_variants_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."provider_availability_slots" add constraint "provider_availability_slots_pkey" PRIMARY KEY using index "provider_availability_slots_pkey";

alter table "public"."providers" add constraint "providers_pkey" PRIMARY KEY using index "providers_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."services" add constraint "services_pkey" PRIMARY KEY using index "services_pkey";

alter table "public"."subcategories" add constraint "subcategories_pkey" PRIMARY KEY using index "subcategories_pkey";

alter table "public"."subcategory_custom_fields" add constraint "subcategory_custom_fields_pkey" PRIMARY KEY using index "subcategory_custom_fields_pkey";

alter table "public"."subconcepts" add constraint "subconcepts_pkey" PRIMARY KEY using index "subconcepts_pkey";

alter table "public"."supplier_bank_accounts" add constraint "supplier_bank_accounts_pkey" PRIMARY KEY using index "supplier_bank_accounts_pkey";

alter table "public"."suppliers" add constraint "suppliers_pkey" PRIMARY KEY using index "suppliers_pkey";

alter table "public"."test_force_migration" add constraint "test_force_migration_pkey" PRIMARY KEY using index "test_force_migration_pkey";

alter table "public"."test_sync" add constraint "test_sync_pkey" PRIMARY KEY using index "test_sync_pkey";

alter table "public"."upsell_products" add constraint "upsell_products_pkey" PRIMARY KEY using index "upsell_products_pkey";

alter table "public"."upsells" add constraint "upsells_pkey" PRIMARY KEY using index "upsells_pkey";

alter table "public"."bank_account_verifications" add constraint "bank_account_verifications_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE not valid;

alter table "public"."bank_account_verifications" validate constraint "bank_account_verifications_supplier_id_fkey";

alter table "public"."bank_account_verifications" add constraint "bank_account_verifications_verification_type_check" CHECK ((verification_type = ANY (ARRAY['update'::text, 'delete'::text]))) not valid;

alter table "public"."bank_account_verifications" validate constraint "bank_account_verifications_verification_type_check";

alter table "public"."images" add constraint "images_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."images" validate constraint "images_product_id_fkey";

alter table "public"."orders" add constraint "orders_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL not valid;

alter table "public"."orders" validate constraint "orders_product_id_fkey";

alter table "public"."product_variants" add constraint "product_variants_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."product_variants" validate constraint "product_variants_product_id_fkey";

alter table "public"."products" add constraint "products_subcategory_id_fkey" FOREIGN KEY (subcategory_id) REFERENCES subcategories(id) ON DELETE SET NULL not valid;

alter table "public"."products" validate constraint "products_subcategory_id_fkey";

alter table "public"."products" add constraint "products_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE not valid;

alter table "public"."products" validate constraint "products_supplier_id_fkey";

alter table "public"."provider_availability_slots" add constraint "provider_availability_slots_service_id_fkey" FOREIGN KEY (service_id) REFERENCES services(id) not valid;

alter table "public"."provider_availability_slots" validate constraint "provider_availability_slots_service_id_fkey";

alter table "public"."reviews" add constraint "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5))) not valid;

alter table "public"."reviews" validate constraint "reviews_rating_check";

alter table "public"."reviews" add constraint "reviews_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))) not valid;

alter table "public"."reviews" validate constraint "reviews_status_check";

alter table "public"."reviews" add constraint "reviews_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_supplier_id_fkey";

alter table "public"."services" add constraint "services_provider_id_fkey" FOREIGN KEY (provider_id) REFERENCES providers(id) not valid;

alter table "public"."services" validate constraint "services_provider_id_fkey";

alter table "public"."subcategories" add constraint "subcategories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE not valid;

alter table "public"."subcategories" validate constraint "subcategories_category_id_fkey";

alter table "public"."subcategory_custom_fields" add constraint "subcategory_custom_fields_field_type_check" CHECK ((field_type = ANY (ARRAY['text'::text, 'number'::text, 'boolean'::text, 'select'::text, 'multiselect'::text, 'date'::text]))) not valid;

alter table "public"."subcategory_custom_fields" validate constraint "subcategory_custom_fields_field_type_check";

alter table "public"."subcategory_custom_fields" add constraint "subcategory_custom_fields_subcategory_id_fkey" FOREIGN KEY (subcategory_id) REFERENCES subcategories(id) ON DELETE CASCADE not valid;

alter table "public"."subcategory_custom_fields" validate constraint "subcategory_custom_fields_subcategory_id_fkey";

alter table "public"."subconcepts" add constraint "subconcepts_concept_id_fkey" FOREIGN KEY (concept_id) REFERENCES concepts(id) ON DELETE CASCADE not valid;

alter table "public"."subconcepts" validate constraint "subconcepts_concept_id_fkey";

alter table "public"."supplier_bank_accounts" add constraint "supplier_bank_accounts_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE not valid;

alter table "public"."supplier_bank_accounts" validate constraint "supplier_bank_accounts_supplier_id_fkey";

alter table "public"."supplier_bank_accounts" add constraint "supplier_bank_accounts_supplier_id_key" UNIQUE using index "supplier_bank_accounts_supplier_id_key";

alter table "public"."supplier_bank_accounts" add constraint "supplier_bank_accounts_verification_status_check" CHECK ((verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text]))) not valid;

alter table "public"."supplier_bank_accounts" validate constraint "supplier_bank_accounts_verification_status_check";

alter table "public"."suppliers" add constraint "suppliers_tax_id_key" UNIQUE using index "suppliers_tax_id_key";

alter table "public"."upsell_products" add constraint "upsell_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."upsell_products" validate constraint "upsell_products_product_id_fkey";

alter table "public"."upsell_products" add constraint "upsell_products_upsell_id_fkey" FOREIGN KEY (upsell_id) REFERENCES upsells(id) ON DELETE CASCADE not valid;

alter table "public"."upsell_products" validate constraint "upsell_products_upsell_id_fkey";

alter table "public"."upsell_products" add constraint "upsell_products_upsell_id_product_id_key" UNIQUE using index "upsell_products_upsell_id_product_id_key";

alter table "public"."upsells" add constraint "upsells_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE not valid;

alter table "public"."upsells" validate constraint "upsells_supplier_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.check_service_availability(p_service_id uuid, p_date date, p_start_time time without time zone, p_duration_minutes integer DEFAULT 120, p_location text DEFAULT NULL::text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_calendar_connected boolean;
  v_calendar_active boolean;
  v_service_areas text[];
  v_setup_time_minutes integer;
  v_teardown_time_minutes integer;
  required_start_time time;
  required_end_time time;
  slot_available boolean := false;
BEGIN
  -- שליפת פרטי השירות והספק
  SELECT 
    p.calendar_connected, 
    p.calendar_active, 
    s.service_areas,
    s.setup_time_minutes,
    s.teardown_time_minutes
  INTO 
    v_calendar_connected, 
    v_calendar_active, 
    v_service_areas,
    v_setup_time_minutes,
    v_teardown_time_minutes
  FROM services s 
  JOIN providers p ON s.provider_id = p.id 
  WHERE s.id = p_service_id;
  
  -- בדיקה שהיומן מחובר ופעיל
  IF NOT (v_calendar_connected AND v_calendar_active) THEN
    RETURN false;
  END IF;
  
  -- בדיקת אזור שירות אם צוין מיקום
  IF p_location IS NOT NULL AND v_service_areas IS NOT NULL THEN
    IF NOT (p_location = ANY(v_service_areas)) THEN
      RETURN false;
    END IF;
  END IF;
  
  -- חישוב זמן התחלה וסיום הנדרש (כולל זמני הכנה)
  required_start_time := p_start_time - (COALESCE(v_setup_time_minutes, 30) || ' minutes')::interval;
  required_end_time := p_start_time + (p_duration_minutes + COALESCE(v_teardown_time_minutes, 15) || ' minutes')::interval;
  
  -- בדיקת זמינות בטבלת הזמינות
  SELECT EXISTS (
    SELECT 1 FROM provider_availability_slots pas
    WHERE pas.service_id = p_service_id
    AND pas.date = p_date
    AND pas.start_time <= required_start_time::time
    AND pas.end_time >= required_end_time::time
    AND pas.is_available = true
    AND pas.current_bookings < pas.max_concurrent_bookings
  ) INTO slot_available;
  
  RETURN slot_available;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_current_user_role()
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  RETURN (
    SELECT role
    FROM public.user_roles
    WHERE user_id = auth.uid()
    AND is_active = true
    LIMIT 1
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, display_name, email)
  VALUES (new.id, new.raw_user_meta_data->>'name', new.email);
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  RETURN (
    SELECT EXISTS(
      SELECT 1 
      FROM public.user_roles 
      WHERE user_id = auth.uid() 
      AND role IN ('מנהל-על', 'מנהל') 
      AND is_active = true
    )
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_service_active(service_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT 
    s.is_visible = true 
    AND s.base_price IS NOT NULL 
    AND s.base_price > 0
    AND s.has_calendar_integration = true
  FROM public.services s 
  WHERE s.id = service_id;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_lottery_check()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
    participant_record RECORD;
    total_reviews INTEGER;
BEGIN
    -- עדכון מספר הביקורות של המשתמש
    INSERT INTO lottery_participants (customer_email, reviews_count, last_review_date)
    VALUES (NEW.customer_email, 1, NEW.created_at)
    ON CONFLICT (customer_email) 
    DO UPDATE SET 
        reviews_count = lottery_participants.reviews_count + 1,
        last_review_date = NEW.created_at;
    
    -- בדיקה אם הגענו ל-500 ביקורות
    SELECT SUM(reviews_count) INTO total_reviews FROM lottery_participants WHERE is_eligible = true;
    
    IF total_reviews >= 500 THEN
        -- בחירת זוכה אקראי
        SELECT * INTO participant_record 
        FROM lottery_participants 
        WHERE is_eligible = true 
        ORDER BY RANDOM() 
        LIMIT 1;
        
        -- הוספת הזוכה לטבלה
        INSERT INTO lottery_winners (customer_email) VALUES (participant_record.customer_email);
        
        -- איפוס הזכאות לכל המשתתפים
        UPDATE lottery_participants SET is_eligible = false;
        
        -- יצירת מחזור חדש
        UPDATE lottery_participants SET is_eligible = true, reviews_count = 0;
    END IF;
    
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_timestamp()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."audiences" to "anon";

grant insert on table "public"."audiences" to "anon";

grant references on table "public"."audiences" to "anon";

grant select on table "public"."audiences" to "anon";

grant trigger on table "public"."audiences" to "anon";

grant truncate on table "public"."audiences" to "anon";

grant update on table "public"."audiences" to "anon";

grant delete on table "public"."audiences" to "authenticated";

grant insert on table "public"."audiences" to "authenticated";

grant references on table "public"."audiences" to "authenticated";

grant select on table "public"."audiences" to "authenticated";

grant trigger on table "public"."audiences" to "authenticated";

grant truncate on table "public"."audiences" to "authenticated";

grant update on table "public"."audiences" to "authenticated";

grant delete on table "public"."audiences" to "service_role";

grant insert on table "public"."audiences" to "service_role";

grant references on table "public"."audiences" to "service_role";

grant select on table "public"."audiences" to "service_role";

grant trigger on table "public"."audiences" to "service_role";

grant truncate on table "public"."audiences" to "service_role";

grant update on table "public"."audiences" to "service_role";

grant delete on table "public"."bank_account_verifications" to "anon";

grant insert on table "public"."bank_account_verifications" to "anon";

grant references on table "public"."bank_account_verifications" to "anon";

grant select on table "public"."bank_account_verifications" to "anon";

grant trigger on table "public"."bank_account_verifications" to "anon";

grant truncate on table "public"."bank_account_verifications" to "anon";

grant update on table "public"."bank_account_verifications" to "anon";

grant delete on table "public"."bank_account_verifications" to "authenticated";

grant insert on table "public"."bank_account_verifications" to "authenticated";

grant references on table "public"."bank_account_verifications" to "authenticated";

grant select on table "public"."bank_account_verifications" to "authenticated";

grant trigger on table "public"."bank_account_verifications" to "authenticated";

grant truncate on table "public"."bank_account_verifications" to "authenticated";

grant update on table "public"."bank_account_verifications" to "authenticated";

grant delete on table "public"."bank_account_verifications" to "service_role";

grant insert on table "public"."bank_account_verifications" to "service_role";

grant references on table "public"."bank_account_verifications" to "service_role";

grant select on table "public"."bank_account_verifications" to "service_role";

grant trigger on table "public"."bank_account_verifications" to "service_role";

grant truncate on table "public"."bank_account_verifications" to "service_role";

grant update on table "public"."bank_account_verifications" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."category_fields" to "anon";

grant insert on table "public"."category_fields" to "anon";

grant references on table "public"."category_fields" to "anon";

grant select on table "public"."category_fields" to "anon";

grant trigger on table "public"."category_fields" to "anon";

grant truncate on table "public"."category_fields" to "anon";

grant update on table "public"."category_fields" to "anon";

grant delete on table "public"."category_fields" to "authenticated";

grant insert on table "public"."category_fields" to "authenticated";

grant references on table "public"."category_fields" to "authenticated";

grant select on table "public"."category_fields" to "authenticated";

grant trigger on table "public"."category_fields" to "authenticated";

grant truncate on table "public"."category_fields" to "authenticated";

grant update on table "public"."category_fields" to "authenticated";

grant delete on table "public"."category_fields" to "service_role";

grant insert on table "public"."category_fields" to "service_role";

grant references on table "public"."category_fields" to "service_role";

grant select on table "public"."category_fields" to "service_role";

grant trigger on table "public"."category_fields" to "service_role";

grant truncate on table "public"."category_fields" to "service_role";

grant update on table "public"."category_fields" to "service_role";

grant delete on table "public"."concepts" to "anon";

grant insert on table "public"."concepts" to "anon";

grant references on table "public"."concepts" to "anon";

grant select on table "public"."concepts" to "anon";

grant trigger on table "public"."concepts" to "anon";

grant truncate on table "public"."concepts" to "anon";

grant update on table "public"."concepts" to "anon";

grant delete on table "public"."concepts" to "authenticated";

grant insert on table "public"."concepts" to "authenticated";

grant references on table "public"."concepts" to "authenticated";

grant select on table "public"."concepts" to "authenticated";

grant trigger on table "public"."concepts" to "authenticated";

grant truncate on table "public"."concepts" to "authenticated";

grant update on table "public"."concepts" to "authenticated";

grant delete on table "public"."concepts" to "service_role";

grant insert on table "public"."concepts" to "service_role";

grant references on table "public"."concepts" to "service_role";

grant select on table "public"."concepts" to "service_role";

grant trigger on table "public"."concepts" to "service_role";

grant truncate on table "public"."concepts" to "service_role";

grant update on table "public"."concepts" to "service_role";

grant delete on table "public"."empowerment_products" to "anon";

grant insert on table "public"."empowerment_products" to "anon";

grant references on table "public"."empowerment_products" to "anon";

grant select on table "public"."empowerment_products" to "anon";

grant trigger on table "public"."empowerment_products" to "anon";

grant truncate on table "public"."empowerment_products" to "anon";

grant update on table "public"."empowerment_products" to "anon";

grant delete on table "public"."empowerment_products" to "authenticated";

grant insert on table "public"."empowerment_products" to "authenticated";

grant references on table "public"."empowerment_products" to "authenticated";

grant select on table "public"."empowerment_products" to "authenticated";

grant trigger on table "public"."empowerment_products" to "authenticated";

grant truncate on table "public"."empowerment_products" to "authenticated";

grant update on table "public"."empowerment_products" to "authenticated";

grant delete on table "public"."empowerment_products" to "service_role";

grant insert on table "public"."empowerment_products" to "service_role";

grant references on table "public"."empowerment_products" to "service_role";

grant select on table "public"."empowerment_products" to "service_role";

grant trigger on table "public"."empowerment_products" to "service_role";

grant truncate on table "public"."empowerment_products" to "service_role";

grant update on table "public"."empowerment_products" to "service_role";

grant delete on table "public"."images" to "anon";

grant insert on table "public"."images" to "anon";

grant references on table "public"."images" to "anon";

grant select on table "public"."images" to "anon";

grant trigger on table "public"."images" to "anon";

grant truncate on table "public"."images" to "anon";

grant update on table "public"."images" to "anon";

grant delete on table "public"."images" to "authenticated";

grant insert on table "public"."images" to "authenticated";

grant references on table "public"."images" to "authenticated";

grant select on table "public"."images" to "authenticated";

grant trigger on table "public"."images" to "authenticated";

grant truncate on table "public"."images" to "authenticated";

grant update on table "public"."images" to "authenticated";

grant delete on table "public"."images" to "service_role";

grant insert on table "public"."images" to "service_role";

grant references on table "public"."images" to "service_role";

grant select on table "public"."images" to "service_role";

grant trigger on table "public"."images" to "service_role";

grant truncate on table "public"."images" to "service_role";

grant update on table "public"."images" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."product_variants" to "anon";

grant insert on table "public"."product_variants" to "anon";

grant references on table "public"."product_variants" to "anon";

grant select on table "public"."product_variants" to "anon";

grant trigger on table "public"."product_variants" to "anon";

grant truncate on table "public"."product_variants" to "anon";

grant update on table "public"."product_variants" to "anon";

grant delete on table "public"."product_variants" to "authenticated";

grant insert on table "public"."product_variants" to "authenticated";

grant references on table "public"."product_variants" to "authenticated";

grant select on table "public"."product_variants" to "authenticated";

grant trigger on table "public"."product_variants" to "authenticated";

grant truncate on table "public"."product_variants" to "authenticated";

grant update on table "public"."product_variants" to "authenticated";

grant delete on table "public"."product_variants" to "service_role";

grant insert on table "public"."product_variants" to "service_role";

grant references on table "public"."product_variants" to "service_role";

grant select on table "public"."product_variants" to "service_role";

grant trigger on table "public"."product_variants" to "service_role";

grant truncate on table "public"."product_variants" to "service_role";

grant update on table "public"."product_variants" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."provider_availability_slots" to "anon";

grant insert on table "public"."provider_availability_slots" to "anon";

grant references on table "public"."provider_availability_slots" to "anon";

grant select on table "public"."provider_availability_slots" to "anon";

grant trigger on table "public"."provider_availability_slots" to "anon";

grant truncate on table "public"."provider_availability_slots" to "anon";

grant update on table "public"."provider_availability_slots" to "anon";

grant delete on table "public"."provider_availability_slots" to "authenticated";

grant insert on table "public"."provider_availability_slots" to "authenticated";

grant references on table "public"."provider_availability_slots" to "authenticated";

grant select on table "public"."provider_availability_slots" to "authenticated";

grant trigger on table "public"."provider_availability_slots" to "authenticated";

grant truncate on table "public"."provider_availability_slots" to "authenticated";

grant update on table "public"."provider_availability_slots" to "authenticated";

grant delete on table "public"."provider_availability_slots" to "service_role";

grant insert on table "public"."provider_availability_slots" to "service_role";

grant references on table "public"."provider_availability_slots" to "service_role";

grant select on table "public"."provider_availability_slots" to "service_role";

grant trigger on table "public"."provider_availability_slots" to "service_role";

grant truncate on table "public"."provider_availability_slots" to "service_role";

grant update on table "public"."provider_availability_slots" to "service_role";

grant delete on table "public"."providers" to "anon";

grant insert on table "public"."providers" to "anon";

grant references on table "public"."providers" to "anon";

grant select on table "public"."providers" to "anon";

grant trigger on table "public"."providers" to "anon";

grant truncate on table "public"."providers" to "anon";

grant update on table "public"."providers" to "anon";

grant delete on table "public"."providers" to "authenticated";

grant insert on table "public"."providers" to "authenticated";

grant references on table "public"."providers" to "authenticated";

grant select on table "public"."providers" to "authenticated";

grant trigger on table "public"."providers" to "authenticated";

grant truncate on table "public"."providers" to "authenticated";

grant update on table "public"."providers" to "authenticated";

grant delete on table "public"."providers" to "service_role";

grant insert on table "public"."providers" to "service_role";

grant references on table "public"."providers" to "service_role";

grant select on table "public"."providers" to "service_role";

grant trigger on table "public"."providers" to "service_role";

grant truncate on table "public"."providers" to "service_role";

grant update on table "public"."providers" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

grant delete on table "public"."services" to "anon";

grant insert on table "public"."services" to "anon";

grant references on table "public"."services" to "anon";

grant select on table "public"."services" to "anon";

grant trigger on table "public"."services" to "anon";

grant truncate on table "public"."services" to "anon";

grant update on table "public"."services" to "anon";

grant delete on table "public"."services" to "authenticated";

grant insert on table "public"."services" to "authenticated";

grant references on table "public"."services" to "authenticated";

grant select on table "public"."services" to "authenticated";

grant trigger on table "public"."services" to "authenticated";

grant truncate on table "public"."services" to "authenticated";

grant update on table "public"."services" to "authenticated";

grant delete on table "public"."services" to "service_role";

grant insert on table "public"."services" to "service_role";

grant references on table "public"."services" to "service_role";

grant select on table "public"."services" to "service_role";

grant trigger on table "public"."services" to "service_role";

grant truncate on table "public"."services" to "service_role";

grant update on table "public"."services" to "service_role";

grant delete on table "public"."subcategories" to "anon";

grant insert on table "public"."subcategories" to "anon";

grant references on table "public"."subcategories" to "anon";

grant select on table "public"."subcategories" to "anon";

grant trigger on table "public"."subcategories" to "anon";

grant truncate on table "public"."subcategories" to "anon";

grant update on table "public"."subcategories" to "anon";

grant delete on table "public"."subcategories" to "authenticated";

grant insert on table "public"."subcategories" to "authenticated";

grant references on table "public"."subcategories" to "authenticated";

grant select on table "public"."subcategories" to "authenticated";

grant trigger on table "public"."subcategories" to "authenticated";

grant truncate on table "public"."subcategories" to "authenticated";

grant update on table "public"."subcategories" to "authenticated";

grant delete on table "public"."subcategories" to "service_role";

grant insert on table "public"."subcategories" to "service_role";

grant references on table "public"."subcategories" to "service_role";

grant select on table "public"."subcategories" to "service_role";

grant trigger on table "public"."subcategories" to "service_role";

grant truncate on table "public"."subcategories" to "service_role";

grant update on table "public"."subcategories" to "service_role";

grant delete on table "public"."subcategory_custom_fields" to "anon";

grant insert on table "public"."subcategory_custom_fields" to "anon";

grant references on table "public"."subcategory_custom_fields" to "anon";

grant select on table "public"."subcategory_custom_fields" to "anon";

grant trigger on table "public"."subcategory_custom_fields" to "anon";

grant truncate on table "public"."subcategory_custom_fields" to "anon";

grant update on table "public"."subcategory_custom_fields" to "anon";

grant delete on table "public"."subcategory_custom_fields" to "authenticated";

grant insert on table "public"."subcategory_custom_fields" to "authenticated";

grant references on table "public"."subcategory_custom_fields" to "authenticated";

grant select on table "public"."subcategory_custom_fields" to "authenticated";

grant trigger on table "public"."subcategory_custom_fields" to "authenticated";

grant truncate on table "public"."subcategory_custom_fields" to "authenticated";

grant update on table "public"."subcategory_custom_fields" to "authenticated";

grant delete on table "public"."subcategory_custom_fields" to "service_role";

grant insert on table "public"."subcategory_custom_fields" to "service_role";

grant references on table "public"."subcategory_custom_fields" to "service_role";

grant select on table "public"."subcategory_custom_fields" to "service_role";

grant trigger on table "public"."subcategory_custom_fields" to "service_role";

grant truncate on table "public"."subcategory_custom_fields" to "service_role";

grant update on table "public"."subcategory_custom_fields" to "service_role";

grant delete on table "public"."subconcepts" to "anon";

grant insert on table "public"."subconcepts" to "anon";

grant references on table "public"."subconcepts" to "anon";

grant select on table "public"."subconcepts" to "anon";

grant trigger on table "public"."subconcepts" to "anon";

grant truncate on table "public"."subconcepts" to "anon";

grant update on table "public"."subconcepts" to "anon";

grant delete on table "public"."subconcepts" to "authenticated";

grant insert on table "public"."subconcepts" to "authenticated";

grant references on table "public"."subconcepts" to "authenticated";

grant select on table "public"."subconcepts" to "authenticated";

grant trigger on table "public"."subconcepts" to "authenticated";

grant truncate on table "public"."subconcepts" to "authenticated";

grant update on table "public"."subconcepts" to "authenticated";

grant delete on table "public"."subconcepts" to "service_role";

grant insert on table "public"."subconcepts" to "service_role";

grant references on table "public"."subconcepts" to "service_role";

grant select on table "public"."subconcepts" to "service_role";

grant trigger on table "public"."subconcepts" to "service_role";

grant truncate on table "public"."subconcepts" to "service_role";

grant update on table "public"."subconcepts" to "service_role";

grant delete on table "public"."supplier_bank_accounts" to "anon";

grant insert on table "public"."supplier_bank_accounts" to "anon";

grant references on table "public"."supplier_bank_accounts" to "anon";

grant select on table "public"."supplier_bank_accounts" to "anon";

grant trigger on table "public"."supplier_bank_accounts" to "anon";

grant truncate on table "public"."supplier_bank_accounts" to "anon";

grant update on table "public"."supplier_bank_accounts" to "anon";

grant delete on table "public"."supplier_bank_accounts" to "authenticated";

grant insert on table "public"."supplier_bank_accounts" to "authenticated";

grant references on table "public"."supplier_bank_accounts" to "authenticated";

grant select on table "public"."supplier_bank_accounts" to "authenticated";

grant trigger on table "public"."supplier_bank_accounts" to "authenticated";

grant truncate on table "public"."supplier_bank_accounts" to "authenticated";

grant update on table "public"."supplier_bank_accounts" to "authenticated";

grant delete on table "public"."supplier_bank_accounts" to "service_role";

grant insert on table "public"."supplier_bank_accounts" to "service_role";

grant references on table "public"."supplier_bank_accounts" to "service_role";

grant select on table "public"."supplier_bank_accounts" to "service_role";

grant trigger on table "public"."supplier_bank_accounts" to "service_role";

grant truncate on table "public"."supplier_bank_accounts" to "service_role";

grant update on table "public"."supplier_bank_accounts" to "service_role";

grant delete on table "public"."suppliers" to "anon";

grant insert on table "public"."suppliers" to "anon";

grant references on table "public"."suppliers" to "anon";

grant select on table "public"."suppliers" to "anon";

grant trigger on table "public"."suppliers" to "anon";

grant truncate on table "public"."suppliers" to "anon";

grant update on table "public"."suppliers" to "anon";

grant delete on table "public"."suppliers" to "authenticated";

grant insert on table "public"."suppliers" to "authenticated";

grant references on table "public"."suppliers" to "authenticated";

grant select on table "public"."suppliers" to "authenticated";

grant trigger on table "public"."suppliers" to "authenticated";

grant truncate on table "public"."suppliers" to "authenticated";

grant update on table "public"."suppliers" to "authenticated";

grant delete on table "public"."suppliers" to "service_role";

grant insert on table "public"."suppliers" to "service_role";

grant references on table "public"."suppliers" to "service_role";

grant select on table "public"."suppliers" to "service_role";

grant trigger on table "public"."suppliers" to "service_role";

grant truncate on table "public"."suppliers" to "service_role";

grant update on table "public"."suppliers" to "service_role";

grant delete on table "public"."test_force_migration" to "anon";

grant insert on table "public"."test_force_migration" to "anon";

grant references on table "public"."test_force_migration" to "anon";

grant select on table "public"."test_force_migration" to "anon";

grant trigger on table "public"."test_force_migration" to "anon";

grant truncate on table "public"."test_force_migration" to "anon";

grant update on table "public"."test_force_migration" to "anon";

grant delete on table "public"."test_force_migration" to "authenticated";

grant insert on table "public"."test_force_migration" to "authenticated";

grant references on table "public"."test_force_migration" to "authenticated";

grant select on table "public"."test_force_migration" to "authenticated";

grant trigger on table "public"."test_force_migration" to "authenticated";

grant truncate on table "public"."test_force_migration" to "authenticated";

grant update on table "public"."test_force_migration" to "authenticated";

grant delete on table "public"."test_force_migration" to "service_role";

grant insert on table "public"."test_force_migration" to "service_role";

grant references on table "public"."test_force_migration" to "service_role";

grant select on table "public"."test_force_migration" to "service_role";

grant trigger on table "public"."test_force_migration" to "service_role";

grant truncate on table "public"."test_force_migration" to "service_role";

grant update on table "public"."test_force_migration" to "service_role";

grant delete on table "public"."test_sync" to "anon";

grant insert on table "public"."test_sync" to "anon";

grant references on table "public"."test_sync" to "anon";

grant select on table "public"."test_sync" to "anon";

grant trigger on table "public"."test_sync" to "anon";

grant truncate on table "public"."test_sync" to "anon";

grant update on table "public"."test_sync" to "anon";

grant delete on table "public"."test_sync" to "authenticated";

grant insert on table "public"."test_sync" to "authenticated";

grant references on table "public"."test_sync" to "authenticated";

grant select on table "public"."test_sync" to "authenticated";

grant trigger on table "public"."test_sync" to "authenticated";

grant truncate on table "public"."test_sync" to "authenticated";

grant update on table "public"."test_sync" to "authenticated";

grant delete on table "public"."test_sync" to "service_role";

grant insert on table "public"."test_sync" to "service_role";

grant references on table "public"."test_sync" to "service_role";

grant select on table "public"."test_sync" to "service_role";

grant trigger on table "public"."test_sync" to "service_role";

grant truncate on table "public"."test_sync" to "service_role";

grant update on table "public"."test_sync" to "service_role";

grant delete on table "public"."upsell_products" to "anon";

grant insert on table "public"."upsell_products" to "anon";

grant references on table "public"."upsell_products" to "anon";

grant select on table "public"."upsell_products" to "anon";

grant trigger on table "public"."upsell_products" to "anon";

grant truncate on table "public"."upsell_products" to "anon";

grant update on table "public"."upsell_products" to "anon";

grant delete on table "public"."upsell_products" to "authenticated";

grant insert on table "public"."upsell_products" to "authenticated";

grant references on table "public"."upsell_products" to "authenticated";

grant select on table "public"."upsell_products" to "authenticated";

grant trigger on table "public"."upsell_products" to "authenticated";

grant truncate on table "public"."upsell_products" to "authenticated";

grant update on table "public"."upsell_products" to "authenticated";

grant delete on table "public"."upsell_products" to "service_role";

grant insert on table "public"."upsell_products" to "service_role";

grant references on table "public"."upsell_products" to "service_role";

grant select on table "public"."upsell_products" to "service_role";

grant trigger on table "public"."upsell_products" to "service_role";

grant truncate on table "public"."upsell_products" to "service_role";

grant update on table "public"."upsell_products" to "service_role";

grant delete on table "public"."upsells" to "anon";

grant insert on table "public"."upsells" to "anon";

grant references on table "public"."upsells" to "anon";

grant select on table "public"."upsells" to "anon";

grant trigger on table "public"."upsells" to "anon";

grant truncate on table "public"."upsells" to "anon";

grant update on table "public"."upsells" to "anon";

grant delete on table "public"."upsells" to "authenticated";

grant insert on table "public"."upsells" to "authenticated";

grant references on table "public"."upsells" to "authenticated";

grant select on table "public"."upsells" to "authenticated";

grant trigger on table "public"."upsells" to "authenticated";

grant truncate on table "public"."upsells" to "authenticated";

grant update on table "public"."upsells" to "authenticated";

grant delete on table "public"."upsells" to "service_role";

grant insert on table "public"."upsells" to "service_role";

grant references on table "public"."upsells" to "service_role";

grant select on table "public"."upsells" to "service_role";

grant trigger on table "public"."upsells" to "service_role";

grant truncate on table "public"."upsells" to "service_role";

grant update on table "public"."upsells" to "service_role";

create policy "Authenticated users can view audiences"
on "public"."audiences"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Everyone can read audiences"
on "public"."audiences"
as permissive
for select
to public
using (true);


create policy "Select audiences for all"
on "public"."audiences"
as permissive
for select
to public
using (true);


create policy "Suppliers can manage their own bank account verifications"
on "public"."bank_account_verifications"
as permissive
for all
to public
using ((supplier_id = auth.uid()));


create policy "Suppliers can manage their own verifications"
on "public"."bank_account_verifications"
as permissive
for all
to public
using ((supplier_id = auth.uid()));


create policy "Admin can view categories"
on "public"."categories"
as permissive
for select
to public
using ((auth.role() = 'service_role'::text));


create policy "Everyone can read categories"
on "public"."categories"
as permissive
for select
to public
using (true);


create policy "Select categories for all"
on "public"."categories"
as permissive
for select
to public
using (true);


create policy "Allow all read access"
on "public"."category_fields"
as permissive
for select
to public
using (true);


create policy "Select category fields for all"
on "public"."category_fields"
as permissive
for select
to public
using (true);


create policy "Authenticated users can view concepts"
on "public"."concepts"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Everyone can read concepts"
on "public"."concepts"
as permissive
for select
to public
using (true);


create policy "Enable all"
on "public"."empowerment_products"
as permissive
for all
to public
using (true);


create policy "Suppliers can manage their own images"
on "public"."images"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM products
  WHERE ((products.id = images.product_id) AND (products.supplier_id = auth.uid())))));


create policy "Suppliers can view images of their products"
on "public"."images"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM products
  WHERE ((products.id = images.product_id) AND (products.supplier_id = auth.uid())))));


create policy "Suppliers can manage their own orders"
on "public"."orders"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM products
  WHERE ((products.id = orders.product_id) AND (products.supplier_id = auth.uid())))));


create policy "Suppliers can view their own orders"
on "public"."orders"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM products
  WHERE ((products.id = orders.product_id) AND (products.supplier_id = auth.uid())))));


create policy "Suppliers can manage their own product variants"
on "public"."product_variants"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM products
  WHERE ((products.id = product_variants.product_id) AND (products.supplier_id = auth.uid())))));


create policy "Suppliers can manage their own product_variants"
on "public"."product_variants"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM products
  WHERE ((products.id = product_variants.product_id) AND (products.supplier_id = auth.uid())))));


create policy "Select products for all users"
on "public"."products"
as permissive
for select
to public
using (true);


create policy "Select products only if supplier is active"
on "public"."products"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM suppliers
  WHERE ((suppliers.id = products.supplier_id) AND (suppliers.is_active = true) AND (suppliers.is_suspended = false)))));


create policy "Suppliers can manage their own products"
on "public"."products"
as permissive
for all
to public
using ((supplier_id = auth.uid()));


create policy "Allow access to availability slots for authenticated users"
on "public"."provider_availability_slots"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Delete slots for authenticated users"
on "public"."provider_availability_slots"
as permissive
for delete
to public
using ((auth.role() = 'authenticated'::text));


create policy "Insert slots for authenticated users"
on "public"."provider_availability_slots"
as permissive
for insert
to public
with check ((auth.role() = 'authenticated'::text));


create policy "Select slots for authenticated users"
on "public"."provider_availability_slots"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Update slots for authenticated users"
on "public"."provider_availability_slots"
as permissive
for update
to public
using ((auth.role() = 'authenticated'::text));


create policy "Allow access to providers for authenticated users"
on "public"."providers"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Delete providers for authenticated users"
on "public"."providers"
as permissive
for delete
to public
using ((auth.role() = 'authenticated'::text));


create policy "Insert providers for authenticated users"
on "public"."providers"
as permissive
for insert
to public
with check ((auth.role() = 'authenticated'::text));


create policy "Select providers for authenticated users"
on "public"."providers"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Update providers for authenticated users"
on "public"."providers"
as permissive
for update
to public
using ((auth.role() = 'authenticated'::text));


create policy "Suppliers can manage their own reviews"
on "public"."reviews"
as permissive
for all
to public
using ((supplier_id = auth.uid()));


create policy "Suppliers can update their own reviews"
on "public"."reviews"
as permissive
for update
to public
using ((supplier_id = auth.uid()));


create policy "Suppliers can view their own reviews"
on "public"."reviews"
as permissive
for select
to public
using ((supplier_id = auth.uid()));


create policy "Allow access to services for authenticated users"
on "public"."services"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Delete services for authenticated users"
on "public"."services"
as permissive
for delete
to public
using ((auth.role() = 'authenticated'::text));


create policy "Insert services for authenticated users"
on "public"."services"
as permissive
for insert
to public
with check ((auth.role() = 'authenticated'::text));


create policy "Select services for authenticated users"
on "public"."services"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Update services for authenticated users"
on "public"."services"
as permissive
for update
to public
using ((auth.role() = 'authenticated'::text));


create policy "Everyone can read subcategories"
on "public"."subcategories"
as permissive
for select
to public
using (true);


create policy "Select subcategories for all"
on "public"."subcategories"
as permissive
for select
to public
using (true);


create policy "Authenticated users can view subcategory custom fields"
on "public"."subcategory_custom_fields"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Everyone can read subcategory fields"
on "public"."subcategory_custom_fields"
as permissive
for select
to public
using (true);


create policy "Authenticated users can view subconcepts"
on "public"."subconcepts"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


create policy "Everyone can read subconcepts"
on "public"."subconcepts"
as permissive
for select
to public
using (true);


create policy "Suppliers can manage their own bank accounts"
on "public"."supplier_bank_accounts"
as permissive
for all
to public
using ((supplier_id = auth.uid()));


create policy "Allow read active suppliers"
on "public"."suppliers"
as permissive
for select
to public
using (((is_active = true) AND (is_suspended = false)));


create policy "Suppliers can manage their own suppliers"
on "public"."suppliers"
as permissive
for all
to public
using ((id = auth.uid()));


create policy "Suppliers can view their own profile"
on "public"."suppliers"
as permissive
for select
to public
using ((id = auth.uid()));


create policy "Allow all read access"
on "public"."test_force_migration"
as permissive
for select
to public
using (true);


create policy "Allow all read access"
on "public"."test_sync"
as permissive
for select
to public
using (true);


create policy "Suppliers can manage their own upsell_products"
on "public"."upsell_products"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM upsells
  WHERE ((upsells.id = upsell_products.upsell_id) AND (upsells.supplier_id = auth.uid())))));


create policy "Suppliers can manage their upsell products"
on "public"."upsell_products"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM upsells
  WHERE ((upsells.id = upsell_products.upsell_id) AND (upsells.supplier_id = auth.uid())))));


create policy "Suppliers can manage their own upsells"
on "public"."upsells"
as permissive
for all
to public
using ((supplier_id = auth.uid()));


CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_supplier_bank_accounts_updated_at BEFORE UPDATE ON public.supplier_bank_accounts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_upsells_updated_at BEFORE UPDATE ON public.upsells FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


